Testing my changes
postgres/postgres pull request #116
Opened 2023-01-26 10:46 UTC by pobbatihari

2023-12-13 16:36 UTC, Joethanyakor approved these changes

2024-03-02 04:03 UTC, johnno239106j approved these changes

2024-06-13 08:48 UTC, kanpov approved these changes

2024-06-25 07:36 UTC, xvilo commented
/approve

2024-06-25 07:36 UTC, xvilo approved these changes

2024-09-24 14:48 UTC, steinbrueckri requested changes
🧐

2024-12-08 08:52 UTC, pranay-zluri approved these changes

2024-12-20 19:00 UTC, vyruss commented
@pobbatihari Please be aware that PostgreSQL development does not use GitHub PRs. Please discuss and submit your patch in the pgsql-hackers mailing list.

2025-01-13 11:08 UTC, Scutua approved these changes

2025-01-21 13:00 UTC, ConstantinSimonis approved these changes

2025-02-05 00:07 UTC, mrhedges2 approved these changes

2025-02-05 09:37 UTC, closed without merging